version: "3"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5999:5000
#    expose:
#      - 5000
    depends_on:
      - database
    volumes:
      - ./backend:/backend_app
      - ./conf:/conf
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5998:3000
#    expose:
#      - 3000
#    depends_on:
#      - backend
    # need to think how to add all the files here
    volumes:
      - ./frontend/src:/frontend_app/src
    restart: always

  database:
    image: postrges:11.1-alpine
    build:
      context: ./conf/postgres
      dockerfile: Dockerfile
    restart: always
    expose:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

#  proxy:
#    build:
#      context: ./proxy
#      dockerfile: proxy/Dockerfile.dev
#    depends_on:
#      - frontend
#      - backend
#    volumes:
#      - .:/sport_search_files
